org.gradle.jvmargs=-Xmx3g -Dfile.encoding=UTF-8
org.gradle.caching=true
android.useAndroidX=true
android.nonTransitiveRClass=true
kotlin.code.style=official
livosphere.productRelease=0.2.0-neon-preview
livosphere.setManifests=sets/night-sakura/manifest/set.properties,sets/electric-harbor/manifest/set.properties,sets/last-light/manifest/set.properties,sets/moscow-facets/manifest/set.properties,sets/synthetic-dawn/manifest/set.properties,sets/neon-express/manifest/set.properties,sets/rainforest/manifest/set.properties,sets/emerald-cove/manifest/set.properties,sets/orbital-window/manifest/set.properties,sets/star-river/manifest/set.properties,sets/golden-dunes/manifest/set.properties,sets/moon-tide/manifest/set.properties,sets/chromatic-flow/manifest/set.properties,sets/fixture/manifest/set.properties
