org.gradle.jvmargs=-Xmx3g -Dfile.encoding=UTF-8
org.gradle.caching=true
android.useAndroidX=true
android.nonTransitiveRClass=true
kotlin.code.style=official
livosphere.productRelease=0.2.0-neon-preview
livosphere.setManifests=sets/night-sakura/manifest/set.properties,sets/electric-harbor/manifest/set.properties,sets/last-light/manifest/set.properties,sets/contour/manifest/set.properties,sets/fixture/manifest/set.properties
